---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ui
  labels:
    app: crawler
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: ui
  template:
    metadata:
      name: ui
      labels:
        app: crawler
        component: ui
    spec:
      containers:
      - image: alexeydoc/search_engine_ui:master
        name: ui
        env:
          - name: MONGO
            value: mongodb
