---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: crawler
    component: rabbitmq
    service: "true"
spec:
  ports:
  - name: service-port
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: manage-port
    protocol: TCP
    port: 15672
    targetPort: 15672
  selector:
    app: crawler
    component: rabbitmq
